version: '3.8'

services:

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_bnp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    image: testbnpdemo:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: